apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibm-ubiquity-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Delete