apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubiquity-operator
  namespace: ubiquity
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ubiquity-operator
  template:
    metadata:
      labels:
        name: ubiquity-operator
    spec:
      serviceAccountName: ubiquity-operator
      containers:
        - name: ubiquity-operator
          # Replace this with the built image name
          image: stg-artifactory.haifa.ibm.com:5030/ubiquity-operator:v1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ubiquity-operator"
