apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-ubiquity-db
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ubiquity-local-pv
  resources:
    requests:
      storage: 3Gi
