kind: Pod
apiVersion: v1
metadata:
  name: sanity-pod
spec:
  containers:
  - name: container1
    image: alpine:3.8
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
      - name: vol1
        mountPath: "/data"
  restartPolicy: "Never"
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: sanity-pvc
