kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sanity-pvc
  labels:
    pv-name: sanity-pv
  annotations:
    volume.beta.kubernetes.io/storage-class: "gold"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
