apiVersion: batch/v1
kind: Job
metadata:
  name: post-install
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
spec:
  template:
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - name: post-install-hook
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 1001
          image: "{{ .Values.ubiquityHelmUtils.image.repository }}:{{ .Values.ubiquityHelmUtils.image.tag }}"
          imagePullPolicy: {{ .Values.ubiquityHelmUtils.image.pullPolicy }}
          command: ["/usr/bin/hook-executor"]
          args: ["postinstall"]
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
      restartPolicy: Never
      serviceAccount: ubiquity-helm-hook
  backoffLimit: 1
