{{- if .Values.defaultPodSecurityPolicy.enabled }}
{{- if .Values.defaultPodSecurityPolicy.clusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ubiquity-psp-rolebinding
  labels:
{{ include "ibm_storage_enabler_for_containers.helmLabels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.defaultPodSecurityPolicy.clusterRole }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: "system:serviceaccounts:{{ .Release.Namespace }}"
{{- end }}
{{- end }}
